

package ru.itmo.kotlin.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/**
 * This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("testData/ndArray")
@TestDataPath("$PROJECT_ROOT")
public class NdArrayTestGenerated extends AbstractNdArrayTest {
    @Test
    public void testAllFilesPresentInNdArray() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("testData/ndArray"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        runTest("testData/ndArray/simple.kt");
    }
}
